### ISSUE TITLE
Why there is 404 not found?

### ISSUE THREAD

**Issue by xiaoyaoyou9** [karpathy/LLM101n#18]
Every chapter has no content? I want to learn it very much when I heard this new project!

**Comment by qnixsynapse** [comment]
Yeah. Probably because Andrej hasn't uploaded it yet.

**Comment by tetrahedronix** [comment]
9k stars based solely on hype? This repository only has a README

**Comment by leonardoschwartz** [comment]
In case you're not familiar, every github project starts with a first commit that's usually just a README file with the plan for the repository.

And NO, it doesn't have whatever # of stars (who cares!) just because of hype. It does because many of us have experienced and greatly benefited from some of the outstanding educational content that Andrej has created over the years, and think it's a privilege having him as an instructor on this one.

If you don't know the man and his work, it would be prudent to err on the side of caution and think there is maybe a reason why so many people are excited about this, instead of making a fool of yourself with a comment like that (with all due respect, of course).

**Comment by tetrahedronix** [comment]
It's not accurate to say that 

>every GitHub project starts with a first commit that's usually just a README.

Adding a README file is optional, and a repository can indeed start out completely empty

**Comment by ahmedivy** [comment]
> It's not accurate to say that 
> 
> >every GitHub project starts with a first commit that's usually just a README.
> 
> Adding a README file is optional, and a repository can indeed start out completely empty
> 

He says _usually_.

**Comment by Muna0** [comment]
Waiting excitedly!

**Comment by Codie-Petersen** [comment]
I don't know how everyone else found it, but I saw some posts about it and someone saying he "casually open sourced a GitHub repo: "LLM101n: Let's build a Storyteller" 🤯". Which, given the state, is probably done by design. 

I feel like he probably said, "You know what, I should make a repo for people to learn about LLMs so people can educate themselves before saying things on the internet." but people were following him and said something about it to the public before there was any content.

On the plus side, people can contribute now and allow Andrej to just review it, so he doesn't have to do all of the work by himself. I don't know which he prefers though. Sometimes managing contributions is more annoying than just doing it all by yourself or with your small team who knows the entire vision.

**Comment by Codie-Petersen** [comment]
> 9k stars based solely on hype? This repository only has a README

I think it will probably only stay as READMEs. If you look at the links it is only README links in different folders. Maybe he will add some notebooks for code examples later on. But yeah, any fart in the wind from AI rockstars will attract a whole crowd of scent trackers. But, they also might just be starring the repo to watch it. That's what I do half the time.

**Comment by tetrahedronix** [comment]
> I think it will probably only stay as READMEs. If you look at the links it is only README links in different folders. Maybe he will add some notebooks for code examples later on. But yeah, any fart in the wind from AI rockstars will attract a whole crowd of scent trackers. But, they also might just be starring the repo to watch it. That's what I do half the time.

Hype was not the correct word; after all, English is not my native language. The fact is that one can watch a project and give it stars, but these two functions are not very clear to everyone

**Comment by Kshireen** [comment]
Ready  to  begin this journey.

**Comment by dengyunsheng250** [comment]
ready to join it
